### ISSUE TITLE
User can search products to buy

### ISSUE THREAD

**Issue by askingalot** [nss-cohort-37/Bangazon-Site-Blue-Barracudas#4]
**Given** the user is authenticated
**When** the user clicks on the search input field in the navigation bar
**And** the user types the name of a product
**When** pressed the enter key
**Then** products matching the keyword show in the page

**Comment by ajawashington** [comment]
this will be a Index query on the products controller, asp-route on layout page

**Comment by namitamanohar** [comment]
Separate view for the matching products
